[package]
name = "sat-solve"
description = "A Boolean satisfiability problem (SAT) solver"
authors = ["William Rågstad"]
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
crossterm_cursor = "0.4.0"
sat-lib = { path = "sat-lib" }
